const data = [
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'concluido',
    acoes: 'edit',
  },
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'pendente',
    acoes: 'edit',
  },
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'cancelado',
    acoes: 'edit',
  },
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'concluido',
    acoes: 'edit',
  },
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'concluido',
    acoes: 'edit',
  },
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'concluido',
    acoes: 'edit',
  },
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'concluido',
    acoes: 'edit',
  },
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'concluido',
    acoes: 'edit',
  },
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'concluido',
    acoes: 'edit',
  },
  {
    os: 522,
    cliente: 'ENFHATA',
    ced: 'GPA2562',
    bandeira: 'EXTRA',
    tecnico: 'Adalberto Garcia Garces',
    data: '14/02/2021',
    projeto: 'GPA Avulso',
    status: 'concluido',
    acoes: 'edit',
  },
];

export default data;